CREATE TABLE PRODUCT(
    ID       NUMBER PRIMARY KEY,
    NAME     NVARCHAR2(30),
    PRODUCT_GROUP    NVARCHAR2(8),
    BUY_PRICE NUMBER
);



CREATE SEQUENCE PRODUCT_SEQ START WITH 1 INCREMENT BY 1;